### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by MKatereggaExigent** [impyadav/QA-Annotator#9]
Has anyone tried installing this package using `pip install qa-annotator`? This is the error I get:

```
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting qa-annotator
  Using cached QA-Annotator-1.1.0.tar.gz (6.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/fx/vc4fys5s2zx7t3l0b8_l88vm0000gn/T/pip-install-wasod8by/qa-annotator_79e626ea75864a628e46d0d089e554c0/setup.py", line 6, in <module>
          with open('requirements.txt') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by vasilikik198** [comment]
Did you manage to resolve?
